### ISSUE TITLE
Feedback Task Pertemuan 3

### ISSUE THREAD

**Issue by aufaroot18** [SerlyOktaviani/FRONTEND#1]
## Perbaikan

- Data tidak perlu dipindahkan ke controller.

## Improvement (Hal yang bisa ditingkatkan)

- Pada fungsi `map` di `formatUser`, dapat menggunakan spread operator untuk mengupdate object. Ex: ``{ ...user, name: `${title}. ${user.name}` }``

**Comment by SerlyOktaviani** [comment]
Baik ka ,, terimakasih 🙏

Pada tanggal Kam, 21 Apr 2022 19.06, Aufa Billah ***@***.***>
menulis:

**Comment by aufaroot18** [comment]
Sama sama
